reload_templates: false
debug_authorization: false
debug_notfound: false
debug_templates: false
default_locale_name: en 
fanstatic.bottom: true
fanstatic.debug: true
session.type: file
session.data_dir: data/sessions/data
session.lock_dir: data/sessions/lock
session.key: mykey
session.secret: mysecret
session.cookie_on_exception: true
login_providers: alfresco
alfresco.consumer_key: l7xx5266b4ff5b314695bcde7129cda81f79
alfresco.consumer_secret: ba47df33943b4b2f9f993f31c5049dd7
alfresco.scope: public_api
alfresco.network: redturtle.it
